services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./apps/jellyseerr:/app/config
    networks:
      - homelab
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`seer.${DOMAIN_NAME}`)"
      - "traefik.http.routers.jellyseerr.entrypoints=https"
      - "traefik.http.routers.jellyseerr.tls=true"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
      - "glance.name=Jellyseerr"
      - "glance.icon=si:jellyfin"
      - "glance.url=https://seer.${DOMAIN_NAME}"
      - "glance.description=Request movies and shows"

