services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    tmpfs:
      - /transcode:size=512m
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - ${MEDIA_ROOT:-./data/media}/tvseries:/tv
      - ${MEDIA_ROOT:-./data/media}/movies:/movies
      - ${MEDIA_ROOT:-./data/media}/youtube:/youtube:ro
      - ${MEDIA_ROOT:-./data/media}/downloads/complete:/downloads/complete
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8096:8096 # http
      - 8920:8920 # https
      - 7359:7359/udp # client discovery
      - 1900:1900/udp # auto-discovery on local network
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_NAME}`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "glance.name=Jellyfin"
      - "glance.icon=si:jellyfin"
      - "glance.url=https://jellyfin.${DOMAIN_NAME}"
      - "glance.description=Media server"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8096/ || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  jellyfin_config:
  jellyfin_cache:
