services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_HOST=n8n.${DOMAIN_NAME}
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_DISABLE_COMMUNITY_NODES=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - WEBHOOK_URL=https://n8n.${DOMAIN_NAME}/
      - N8N_EDITOR_BASE_URL=https://n8n.${DOMAIN_NAME}/
    volumes:
      - n8n_data:/home/node/.n8n
      - ./apps/n8n/data:/home/node/data
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.${DOMAIN_NAME}`)"
      - "traefik.http.routers.n8n.entrypoints=https"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "glance.name=n8n"
      - "glance.icon=si:n8n"
      - "glance.url=https://n8n.${DOMAIN_NAME}"
      - "glance.description=Automation baby!"

volumes:
  n8n_data:
