services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - open-webui-local:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`aichat.${DOMAIN_NAME}`)"
      - "traefik.http.routers.openwebui.entrypoints=https"
      - "traefik.http.routers.openwebui.tls=true"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
      - "glance.name=OpenWebUI"
      - "glance.icon=mdi:web"
      - "glance.url=https://chat.${DOMAIN_NAME}"
      - "glance.description=Chat with local models"

volumes:
  open-webui-local:

