services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - radarr_config:/config
      - ${MEDIA_ROOT:-./data/media}/movies:/movies
      - ${MEDIA_ROOT:-./data/media}/downloads/complete:/config/downloads/complete
    networks:
      - homelab
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "glance.name=Radarr"
      - "glance.icon=si:radarr"
      - "glance.url=https://radarr.${DOMAIN_NAME}"
      - "glance.description=For movies"

volumes:
  radarr_config:
