services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - DOCKER_API_VERSION=1.44
    restart: unless-stopped
    networks:
      - homelab
    labels:
      - "glance.hide=true"

